export * from './is-instance'
export * from './is-numeric'
export * from './is-boolean'
export * from './is-primitive'
export * from './is-string'
export * from './is-symbol'
export * from './is-type'